# Generated by Django 4.1.1 on 2022-09-07 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Directores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(help_text='Nombre del actor o actriz', max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='directores',
            name='country',
            field=models.CharField(help_text='Pais de origen del director', max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('summary', models.TextField(help_text='Descripción de la pelicula', max_length=200)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Directores.directores')),
                ('performer', models.ManyToManyField(to='Directores.actores')),
            ],
        ),
    ]
