# Generated by Django 4.1.1 on 2022-09-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directores', '0002_actores_directores_country_peliculas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='summary',
            field=models.TextField(help_text='Descripción de la pelicula', max_length=1000),
        ),
    ]
