# Generated by Django 4.1.1 on 2022-09-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directores', '0003_alter_peliculas_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='directores',
            name='born_date',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='year',
            field=models.DateField(max_length=20, null=True),
        ),
    ]
