# Generated by Django 4.1.1 on 2022-09-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directores', '0004_directores_born_date_peliculas_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directores',
            name='born_date',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
