# Generated by Django 4.1.1 on 2022-09-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Directores', '0005_alter_directores_born_date_alter_peliculas_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actores',
            new_name='Actor',
        ),
        migrations.RenameModel(
            old_name='Directores',
            new_name='Director',
        ),
        migrations.RenameModel(
            old_name='Peliculas',
            new_name='Movies',
        ),
    ]
