# Generated by Django 4.1.1 on 2022-09-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Directores', '0006_rename_actores_actor_rename_directores_director_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
